### ISSUE TITLE
The script in the readme does not work

### ISSUE THREAD

**Issue by mquandalle** [yebyen/urbit-deb#2]
It seems that the repository URL is wrong.

Also I guess you should add `git-core` as a dependency to `apt-get install` on a fresh debian/ubuntu.

**Comment by kingdonb** [comment]
I will check it out! What release of OS are you on, if you don't mind my
asking?

**Comment by mquandalle** [comment]
Hi, I used Ubuntu 14.04 LTS — but actually the issue is more than the `https://github.com/urbit/urbit` repository doesn’t a `urbit-${ARCH}.diff` file. I think the correct download should be something like this instead:

```sh
$ git clone --recursive --depth 1 https://github.com/yebyen/urbit-deb.git urbit
```

**Comment by yebyen** [comment]
The patch is not strictly necessary, and I include it mostly because I am usually not using Urbit on 64-bit platform, so my devices usually can't map a 29 bit loom, and some other issues that sometimes pop up.  The patch file is from my repo, not theirs.  I have no idea what the standards of debian maintainers would say about this, making one-off patches for different architectures to just make it work.

You would have to copy the patch, or reference it from the location where you have cloned my urbit-deb repo.  (The assumption I made is that you already cloned my repo, and now you need to fetch github.com/urbit/urbit -- your approach looks like it would take care of that.)

I will update the block of commands in the README with your approach later today, and not start by assuming that the reader has already cloned my repository.  Could also use a `uname` or `arch` in there for choosing the right patchset.  Thanks!

**Comment by yebyen** [comment]
The script works again.  Breach!
